version: '3.9'

services:
  insurance_db_server:
    image: mysql:8.0
    build:
      context: ./docker/insurance_db_server
      dockerfile: Dockerfile
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: insurance_db_server
    environment:
      MYSQL_ROOT_PASSWORD: secure_password
      MYSQL_DATABASE: insurance_db
      MYSQL_USER: insurance_db_user
      MYSQL_PASSWORD: insurance_db_password
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/insurance_db_server/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - project-network
    
  mockserver:
    image: mockserver/mockserver:latest
    ports:
      - "1080:1080"
    environment:
      MOCKSERVER_PROPERTY_FILE: /config/mockserver.properties
      MOCKSERVER_LOG_LEVEL: INFO
      MOCKSERVER_SERVER_PORT: 1080
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/initializer.json
    volumes:
      - ./docker/catalog-service/config:/config
    networks:
      - project-network

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
     - project-network

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "insurance-quote-received:1:1,insurance-policy-created:1:1"
    networks:
     - project-network

  insurance_quote:
    build:
      context: ./docker/insurance-quote
      dockerfile: Dockerfile
    environment:
      DATASOURCE_URL: jdbc:mysql://insurance_db_server:3306/insurance_db?allowPublicKeyRetrieval=true&useSSL=false
      DATASOURCE_USERNAME: insurance_db_user
      DATASOURCE_PASSWORD: insurance_db_password
    ports:
      - "9000:9000"
    volumes:
      - ./docker/insurance-quote:/opt/insurance-quote
    networks:
     - project-network

networks:
  project-network:

volumes:
  db_data: